import "../globals.css";
import localFont from "next/font/local";
import Direction from "@/components/radixUi/Direction";
import CartProvider from "@/redux/features/providers/CartProvider";
import PersistGateProvider from "@/redux/features/providers/PersistGateProvider";
import AdminPanelLayout from "@/components/layout/Admin/AdminPanelLayout";
import AuthProvider from "../../components/layout/AuthProvider";

const myFont = localFont({
  src: [
    {
      path: "../../../public/fonts/Shabnam-Thin.woff2",
      weight: "100",
      style: "normal",
    },
    {
      path: "../../../public/fonts/Shabnam-Light.woff2",
      weight: "200",
      style: "normal",
    },
    {
      path: "../../../public/fonts/Shabnam-Medium.woff2",
      weight: "300",
      style: "normal",
    },
    {
      path: "../../../public/fonts/Shabnam.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../../public/fonts/Shabnam-Bold.woff2",
      weight: "600",
      style: "normal",
    },
  ],
  display: "swap",
});

export const metadata = {
  title: "پنل ادمین هومن‌آی‌تی",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl" className="bg-[#cecece]">
      <Direction>
        <body className={myFont.className}>
          <CartProvider>
            <PersistGateProvider>
              <AuthProvider>
                <AdminPanelLayout>{children}</AdminPanelLayout>
              </AuthProvider>
            </PersistGateProvider>
          </CartProvider>
        </body>
      </Direction>
    </html>
  );
}
